### ISSUE TITLE
Check that xref is using nbsp between say "Theorem" and "2.1"

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/ww-mbx#5]
I submitted a pull request to WeBWorK to get nbsp, ndash, and mdash. Once this goes through, can we get the nbsp to be used properly in an xref with autoname="yes"?

https://github.com/openwebwork/pg/pull/236

**Comment by rbeezer** [comment]
This should now be ship-shape.  Though testing has been a bit cursory.

At e860d0f8 and https://github.com/rbeezer/mathbook/commit/84c0f38d8235b31d8754bdaa05a443ef7e4a139c
