### ISSUE TITLE
Converter blurb closing line

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/ww-mbx#6]
Consider dropping the closing `*#` at the end of lines in the converter blurb. WeBWorK's in-house editor does not use monospace font for whatever reason. And the blurb looks a bit unprofessional because of the irregular placement of the `*#`.

**Comment by rbeezer** [comment]
Changed here at 6c7a2cc2 with a bigger change in MathBook XML at https://github.com/rbeezer/mathbook/commit/d5865e7e26ef9635845316480ab388a7b95ab9e9
